export const purchasesActionTypes = {
    GET_PURCHASES_REQUEST:"GET_PURCHASES_REQUEST",
    GET_PURCHASES_SUCCESS:" GET_PURCHASES_SUCCESS",
    GET_PURCHASES_FAILED:"GET_PURCHASES_FAILED",


    CREATE_PURCHASES_REQUEST:"CREATE_PURCHASES_REQUEST",
    CREATE_PURCHASES_SUCCESS:" CREATE_PURCHASES_SUCCESS",
    CREATE_PURCHASES_FAILED:"CREATE_PURCHASES_FAILED",


    UPDATE_PURCHASES_REQUEST:"UPDATE_PURCHASES_REQUEST",
    UPDATE_PURCHASES_SUCCESS:" UPDATE_PURCHASES_SUCCESS",
    UPDATE_PURCHASES_FAILED:"UPDATE_PURCHASES_FAILED",

    DELETE_PURCHASES_REQUEST:"DELETE_PURCHASES_REQUEST",
    DELETE_PURCHASES_SUCCESS:" DELETE_PURCHASES_SUCCESS",
    DELETE_PURCHASES_FAILED:"DELETE_PURCHASES_FAILED",

  }